const translations = {
    es: {
      title: "Bienvenidos a Claro Argentina",
      packTitle: "SIM Card + 25 GB de datos móviles por 30 días",
      packDescription: "La mejor opción para mantenerte conectado mientras exploras Argentina.",
      faqTitle: "Información Importante",
      requisitos: "¿Cuáles son los requisitos?",
      requisitosAceptados: "✔️ Se requiere:",
      requisitosNoAceptados: "❌ No se acepta:",
      aceptados: ["Pasaporte físico", "Tarjeta de crédito física"],
      rechazados: ["Fotografía del pasaporte", "Débito o efectivo"],
      recargas: "¿Cómo hago recargas y consulto los consumos?",
      recargasInfo: "Ingresando a la web: <a href='https://miclaro.claro.com.ar/' target='_blank'>https://miclaro.claro.com.ar/</a>",
      sim: "¿Necesita SIM card física o eSIM?",
      simInfo: "El precio es el mismo $17.000 para ambas opciones.",
      proteccionTitle: "Protege tus pertenencias mientras disfrutas de tu viaje",
      proteccionDescription: "Nuestras correas antirrobo y láminas de protección están diseñadas para tu tranquilidad.",
      argentinaSurprise: "Deja que Argentina te sorprenda",
      productosSubtitle: "Mantén tus dispositivos listos para capturar cada momento.",
      correaCortaTitulo: "Correa Antirrobo Corta",
      correaCortaTexto: "Lleva tu celular seguro en el brazo mientras te mueves libremente.",
      correaCuelloTitulo: "Correa larga Antirrobo",
      correaCuelloTexto: "Ideal para mantener tu celular seguro y siempre a la vista.",
      laminaTitulo: "Láminas de Protección",
      laminaTexto: "Protege la pantalla de tu dispositivo contra rayones y golpes.",
      cargadorTitulo: "Cargadores Compatibles",
      cargadorTexto: "Nunca te quedes sin energía mientras descansas o planeas tu próximo destino.",
      cargadorAutoTitulo: "Cargadores de Auto",
      cargadorAutoTexto: "Perfectos para recorrer las rutas argentinas. Mantén tus dispositivos cargados mientras exploras cada rincón del país.",
      powerbankTitulo: "Power Bank",
      powerbankTexto: "Llévalo contigo a cualquier lugar y mantente conectado, incluso en medio de la aventura.",
    },
    en: {
      title: "Welcome to Claro Argentina",
      packTitle: "SIM Card + 25 GB of Mobile Data for 30 Days",
      packDescription: "The best option to stay connected while exploring Argentina.",
      faqTitle: "Important Information",
      requisitos: "What are the requirements?",
      requisitosAceptados: "✔️ Required:",
      requisitosNoAceptados: "❌ Not accepted:",
      aceptados: ["Physical passport", "Physical credit card"],
      rechazados: ["Passport photo", "Debit or cash"],
      recargas: "How do I recharge and check usage?",
      recargasInfo: "Go to the website: <a href='https://miclaro.claro.com.ar/' target='_blank'>https://miclaro.claro.com.ar/</a>",
      sim: "Do you need a physical SIM card or eSIM?",
      simInfo: "The price is the same $17,000 for both options.",
      proteccionTitle: "Protect your belongings while enjoying your trip",
      proteccionDescription: "Our anti-theft straps and protective films are designed for your peace of mind.",
      argentinaSurprise: "Let Argentina surprise you",
      productosSubtitle: "Keep your devices ready to capture every moment.",
      correaCortaTitulo: "Short Anti-Theft Strap",
      correaCortaTexto: "Keep your phone secure on your arm while moving freely.",
      correaCuelloTitulo: "Long Anti-Theft Strap",
      correaCuelloTexto: "Ideal for keeping your phone safe and always within reach.",
      laminaTitulo: "Protective Films",
      laminaTexto: "Protect your device's screen from scratches and impacts.",
      cargadorTitulo: "Compatible Chargers",
      cargadorTexto: "Never run out of energy while resting or planning your next destination.",
      cargadorAutoTitulo: "Car Chargers",
      cargadorAutoTexto: "Perfect for exploring Argentina's roads. Keep your devices charged while you travel.",
      powerbankTitulo: "Power Bank",
      powerbankTexto: "Take it with you anywhere and stay connected, even in the middle of your adventure.",
    },
    ru: {
      title: "Добро пожаловать в Claro Argentina",
      packTitle: "SIM-карта + 25 ГБ мобильного интернета на 30 дней",
      packDescription: "Лучший способ оставаться на связи во время путешествия по Аргентине.",
      faqTitle: "Важная информация",
      requisitos: "Какие требования?",
      requisitosAceptados: "✔️ Требуется:",
      requisitosNoAceptados: "❌ Не принимается:",
      aceptados: ["Физический паспорт", "Физическая кредитная карта"],
      rechazados: ["Фотография паспорта", "Дебет или наличные"],
      recargas: "Как пополнить счет и проверить использование?",
      recargasInfo: "Перейдите на сайт: <a href='https://miclaro.claro.com.ar/' target='_blank'>https://miclaro.claro.com.ar/</a>",
      sim: "Нужна физическая SIM-карта или eSIM?",
      simInfo: "Цена одинакова: 17 000 песо для обоих вариантов.",
      proteccionTitle: "Защитите свои вещи во время путешествия",
      proteccionDescription: "Наши ремни против кражи и защитные пленки созданы для вашего спокойствия.",
      argentinaSurprise: "Пусть Аргентина вас удивит",
      productosSubtitle: "Держите свои устройства готовыми к каждому моменту.",
      correaCortaTitulo: "Короткий ремешок против краж",
      correaCortaTexto: "Держите телефон в безопасности на руке, перемещаясь свободно.",
      correaCuelloTitulo: "Длинный ремешок против краж",
      correaCuelloTexto: "Идеально для сохранения телефона в безопасности и на виду.",
      laminaTitulo: "Защитные пленки",
      laminaTexto: "Защитите экран устройства от царапин и ударов.",
      cargadorTitulo: "Совместимые зарядные устройства",
      cargadorTexto: "Не оставайтесь без энергии, отдыхая или планируя следующую поездку.",
      cargadorAutoTitulo: "Автомобильные зарядные устройства",
      cargadorAutoTexto: "Идеально для путешествий по дорогам Аргентины. Заряжайте устройства, исследуя страну.",
      powerbankTitulo: "Повербанк",
      powerbankTexto: "Берите с собой куда угодно и оставайтесь на связи даже в середине приключения.",
    },
    zh: {
      title: "欢迎来到 Claro Argentina",
      packTitle: "SIM卡 + 25GB流量（有效期30天）",
      packDescription: "在探索阿根廷时保持连接的最佳选择。",
      faqTitle: "重要信息",
      requisitos: "需要什么条件？",
      requisitosAceptados: "✔️ 需要:",
      requisitosNoAceptados: "❌ 不接受:",
      aceptados: ["实体护照", "实体信用卡"],
      rechazados: ["护照照片", "借记卡或现金"],
      recargas: "如何充值和查询使用情况？",
      recargasInfo: "访问网站: <a href='https://miclaro.claro.com.ar/' target='_blank'>https://miclaro.claro.com.ar/</a>",
      sim: "您需要实体 SIM 卡还是 eSIM？",
      simInfo: "两种选项的价格相同，为 17,000 比索。",
      proteccionTitle: "旅行时保护好您的物品",
      proteccionDescription: "我们的防盗带和保护膜让您安心无忧。",
      argentinaSurprise: "让阿根廷带给您惊喜",
      productosSubtitle: "随时准备好您的设备捕捉每一刻。",
      correaCortaTitulo: "短款防盗带",
      correaCortaTexto: "随身携带手机，行动自由，确保安全。",
      correaCuelloTitulo: "长款防盗带",
      correaCuelloTexto: "保持手机安全，随时随地轻松使用。",
      laminaTitulo: "保护膜",
      laminaTexto: "保护设备屏幕免受划痕和冲击。",
      cargadorTitulo: "兼容充电器",
      cargadorTexto: "无论是休息还是计划您的下一步，确保您的设备保持充电。",
      cargadorAutoTitulo: "车载充电器",
      cargadorAutoTexto: "探索阿根廷的道路时的完美选择，确保您的设备始终充满电。",
      powerbankTitulo: "移动电源",
      powerbankTexto: "随身携带，即使在冒险的旅途中也能保持连接。",
    },
    pt: {
      title: "Bem-vindo à Claro Argentina",
      packTitle: "SIM Card + 25 GB de dados móveis por 30 dias",
      packDescription: "A melhor opção para se manter conectado enquanto explora a Argentina.",
      faqTitle: "Informações Importantes",
      requisitos: "Quais são os requisitos?",
      requisitosAceptados: "✔️ Necessário:",
      requisitosNoAceptados: "❌ Não aceito:",
      aceptados: ["Passaporte físico", "Cartão de crédito físico"],
      rechazados: ["Foto do passaporte", "Débito ou dinheiro"],
      recargas: "Como faço recargas e consulto os consumos?",
      recargasInfo: "Acesse o site: <a href='https://miclaro.claro.com.ar/' target='_blank'>https://miclaro.claro.com.ar/</a>",
      sim: "Você precisa de um SIM card físico ou eSIM?",
      simInfo: "O preço é o mesmo: R$17.000 para ambas as opções.",
      proteccionTitle: "Proteja seus pertences enquanto aproveita sua viagem",
      proteccionDescription: "Nossas alças antifurto e películas protetoras foram projetadas para sua tranquilidade.",
      argentinaSurprise: "Deixe a Argentina te surpreender",
      productosSubtitle: "Mantenha seus dispositivos prontos para capturar cada momento.",
      correaCortaTitulo: "Alça Antifurto Curta",
      correaCortaTexto: "Mantenha seu celular seguro no braço enquanto se move livremente.",
      correaCuelloTitulo: "Alça Antifurto Longa",
      correaCuelloTexto: "Ideal para manter seu celular seguro e sempre ao alcance.",
      laminaTitulo: "Películas Protetoras",
      laminaTexto: "Proteja a tela do seu dispositivo contra arranhões e impactos.",
      cargadorTitulo: "Carregadores Compatíveis",
      cargadorTexto: "Nunca fique sem energia enquanto descansa ou planeja seu próximo destino.",
      cargadorAutoTitulo: "Carregadores de Carro",
      cargadorAutoTexto: "Perfeitos para explorar as estradas argentinas. Mantenha seus dispositivos carregados enquanto viaja.",
      powerbankTitulo: "Power Bank",
      powerbankTexto: "Leve com você para qualquer lugar e mantenha-se conectado, mesmo no meio da aventura.",
    },
  };
  


// Función para cambiar el idioma
function cambiarIdioma(lang) {
    const t = translations[lang] || translations["es"];

    // Recorre todas las claves y actualiza el contenido de los elementos correspondientes
    for (const key in t) {
        const element = document.getElementById(key);
        if (element) {
            element.innerHTML = t[key];
        }
    }
}

// Idioma predeterminado al cargar la página
document.addEventListener("DOMContentLoaded", () => cambiarIdioma("es"));
